name: ${plugin.name}
description: ${project.description}
main: ${plugin.mainClass}
version: ${project.version}-${git.commit.id.abbrev}
authors: [The Avicus Network]
commands:
  set:
    usage: /set <name> <value>
    description: Set a setting to a specific value.
  setting:
    usage: /setting <name>
    description: See a setting's value and information.
  settings:
    usage: /settings (page/query)
    description: List available settings.
  toggle:
    usage: /toggle <name>
    description: Toggle a setting between values.